// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXueSQB8-SaZvDht3CVLmpOTXOpv1jmPg',
    appId: '1:1009487566891:web:90d68bddfff6177519326e',
    messagingSenderId: '1009487566891',
    projectId: 'healthai-25f3f',
    authDomain: 'healthai-25f3f.firebaseapp.com',
    storageBucket: 'healthai-25f3f.appspot.com',
    measurementId: 'G-NVJWBDQ17R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIv0JebpnEm-c7ucVin_RHIOljqZuHEvw',
    appId: '1:1009487566891:android:e06b1139116df00a19326e',
    messagingSenderId: '1009487566891',
    projectId: 'healthai-25f3f',
    storageBucket: 'healthai-25f3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv0JwWiHm1etJylCgqEJxSKK7cO-IhEhI',
    appId: '1:1009487566891:ios:9c94492551d1e2cc19326e',
    messagingSenderId: '1009487566891',
    projectId: 'healthai-25f3f',
    storageBucket: 'healthai-25f3f.appspot.com',
    iosBundleId: 'com.healthai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv0JwWiHm1etJylCgqEJxSKK7cO-IhEhI',
    appId: '1:1009487566891:ios:9c94492551d1e2cc19326e',
    messagingSenderId: '1009487566891',
    projectId: 'healthai-25f3f',
    storageBucket: 'healthai-25f3f.appspot.com',
    iosBundleId: 'com.healthai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXueSQB8-SaZvDht3CVLmpOTXOpv1jmPg',
    appId: '1:1009487566891:web:094dd9247a5dbe0919326e',
    messagingSenderId: '1009487566891',
    projectId: 'healthai-25f3f',
    authDomain: 'healthai-25f3f.firebaseapp.com',
    storageBucket: 'healthai-25f3f.appspot.com',
    measurementId: 'G-SJ9KRJPWW0',
  );
}
